<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jeu" nsURI="http://www.Jeu.xtext" nsPrefix="jeu">
  <eClassifiers xsi:type="ecore:EClass" name="Jeu">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieuDebut" lowerBound="1"
        eType="#//Lieu" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieu" upperBound="-1" eType="#//Lieu"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieuFin" lowerBound="1"
        upperBound="-1" eType="#//Lieu" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explorateur" lowerBound="1"
        eType="#//Explorateur" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lieu">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composant" upperBound="-1"
        eType="#//Composant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chemin" upperBound="-1"
        eType="#//Chemin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personnageObligatoire"
        eType="#//PersonnageNonJouable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personnage" upperBound="-1"
        eType="#//PersonnageNonJouable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Explorateur" eSuperTypes="#//Personnage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capaciteObjets" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chemin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieuArrivee" eType="#//Lieu"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonnageNonJouable" eSuperTypes="#//Personnage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="niveau" eType="#//Niveau"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Niveau">
    <eLiterals name="FACILE" literal="FACILE"/>
    <eLiterals name="MOYEN" value="1" literal="MOYEN"/>
    <eLiterals name="DIFFICILE" value="2" literal="DIFFICILE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Objet" eSuperTypes="#//Composant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="poids" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connaissance" eSuperTypes="#//Composant"/>
  <eClassifiers xsi:type="ecore:EClass" name="Personnage" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composant" unique="false"
        upperBound="-1" eType="#//Composant"/>
  </eClassifiers>
</ecore:EPackage>
