<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jeu" nsURI="http://www.Jeu.xtext" nsPrefix="jeu">
  <eClassifiers xsi:type="ecore:EClass" name="Jeu">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nom" eType="#//EString"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieuDebut" eType="#//Lieu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieu" unique="false" upperBound="-1"
        eType="#//Lieu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieuFin" unique="false"
        upperBound="-1" eType="#//Lieu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explorateur" eType="#//Explorateur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nom" eType="#//EString"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EString"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lieu">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nom" eType="#//EString"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composant" unique="false"
        upperBound="-1" eType="#//Composant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chemin" upperBound="-1"
        eType="#//Chemin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personnageObligatoire"
        eType="#//PersonnageNonJouable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personnage" upperBound="-1"
        eType="#//PersonnageNonJouable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Explorateur">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nom" eType="#//EString"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capaciteObjets" eType="#//EInt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composant" unique="false"
        upperBound="-1" eType="#//Composant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chemin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nom" eType="#//EString"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieuArrivee" eType="#//Lieu"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonnageNonJouable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nom" eType="#//EString"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composant" unique="false"
        upperBound="-1" eType="#//Composant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nom" eType="#//EString"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="niveau" eType="#//Niveau"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Niveau">
    <eLiterals name="FACILE" literal="FACILE"/>
    <eLiterals name="MOYEN" value="1" literal="MOYEN"/>
    <eLiterals name="DIFFICILE" value="2" literal="DIFFICILE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nom" eType="#//EString"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBoolean"/>
  <eClassifiers xsi:type="ecore:EClass" name="Objet" eSuperTypes="#//Composant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="poids" eType="#//EInt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connaissance" eSuperTypes="#//Composant"/>
  <eClassifiers xsi:type="ecore:EClass" name="EInt"/>
</ecore:EPackage>
